import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

function json(value) {
  return JSON.stringify(value, null, 2);
}

function routeLabel(routePath) {
  const labelMap = {
    '/': 'Home',
    '/product': 'Product',
    '/pricing': 'Pricing',
    '/services': 'Services',
    '/about': 'About',
    '/emergency': 'Emergency',
    '/quote': 'Get Quote',
    '/contact': 'Contact',
    '/terms': 'Terms & Conditions',
    '/privacy': 'Privacy Policy',
    '/sign-in': 'Sign In',
    '/sign-up': 'Sign Up'
  };

  if (labelMap[routePath]) {
    return labelMap[routePath];
  }

  return routePath
    .replace(/^\//, '')
    .split('/')
    .map((part) => part.replace(/-/g, ' '))
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function routeIdFromPath(routePath) {
  const routeIdMap = {
    '/': 'home',
    '/product': 'product',
    '/pricing': 'pricing',
    '/services': 'services',
    '/about': 'about',
    '/emergency': 'emergency',
    '/quote': 'quote',
    '/contact': 'contact',
    '/terms': 'terms',
    '/privacy': 'privacy',
    '/sign-in': 'sign-in',
    '/sign-up': 'sign-up'
  };

  return routeIdMap[routePath] ?? (routePath.replace(/^\//, '').replace(/\//g, '-') || 'home');
}

async function writeGeneratedFile(appRoot, relativePath, content) {
  const targetPath = path.join(appRoot, relativePath);
  await mkdir(path.dirname(targetPath), { recursive: true });
  await writeFile(targetPath, content, 'utf8');
}

function packageJsonContent(buildPlan) {
  const scripts = {
    dev: buildPlan.scripts.dev,
    build: buildPlan.scripts.build,
    start: 'next start',
    'runtime:detect': 'node scripts/runtime-detect.mjs',
    'dependency:check': 'node scripts/dependency-check.mjs',
    lint: buildPlan.scripts.lint,
    typecheck: buildPlan.scripts.typecheck,
    test: buildPlan.scripts.test,
    'test:unit': buildPlan.scripts['test:unit'],
    'test:a11y': buildPlan.scripts['test:a11y'],
    'e2e:smoke': buildPlan.scripts['e2e:smoke'],
    'e2e:full': buildPlan.scripts['e2e:full'],
    'audit:frontend': buildPlan.scripts['audit:frontend'],
    'release:check': buildPlan.scripts['release:check']
  };

  return `${json({
    name: `generated-${buildPlan.projectSlug}`,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts,
    dependencies: {
      next: '^15.2.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0'
    },
    devDependencies: {
      '@axe-core/playwright': '^4.10.2',
      '@playwright/test': '^1.50.1',
      '@types/node': '^22.10.1',
      '@types/react': '^19.0.2',
      '@types/react-dom': '^19.0.2',
      autoprefixer: '^10.4.20',
      postcss: '^8.4.49',
      tailwindcss: '^3.4.17',
      typescript: '^6.0.3',
      vitest: '^2.1.8'
    }
  })}\n`;
}

function tsconfigContent() {
  return `${json({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'es2022'],
      allowJs: false,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      allowArbitraryExtensions: true,
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      ignoreDeprecations: '6.0',
      plugins: [{ name: 'next' }]
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules']
  })}\n`;
}

function nextConfigContent() {
  return "const nextConfig = {\n  reactStrictMode: true\n};\n\nexport default nextConfig;\n";
}

function postcssConfigContent() {
  return "export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {}\n  }\n};\n";
}

function tailwindConfigContent() {
  return [
    '/** @type {import(\'tailwindcss\').Config} */',
    'export default {',
    "  content: ['./src/**/*.{ts,tsx}', './tests/**/*.{ts,tsx}'],",
    '  theme: {',
    '    extend: {',
    '      colors: {',
    "        canvas: 'var(--color-bg)',",
    "        ink: 'var(--color-fg)',",
    "        accent: 'var(--color-secondary)',",
    "        pop: 'var(--color-accent)'",
    '      },',
    '      boxShadow: {',
    "        mellow: 'var(--shadow-md)'",
    '      },',
    '      borderRadius: {',
    "        hero: 'var(--radius-lg)',",
    "        chip: 'var(--radius-pill)',",
    "        soft: 'var(--radius-md)',",
    "        tight: 'var(--radius-sm)'",
    '      }',
    '    }',
    '  },',
    '  plugins: []',
    '};',
    ''
  ].join('\n');
}

function vitestConfigContent() {
  return [
    "import { defineConfig } from 'vitest/config';",
    '',
    'export default defineConfig({',
    '  test: {',
    "    environment: 'node',",
    "    include: ['tests/unit/**/*.test.ts']",
    '  }',
    '});',
    ''
  ].join('\n');
}

function playwrightConfigContent(port) {
  return [
    "import { defineConfig, devices } from '@playwright/test';",
    '',
    `const port = ${port};`,
    "const serverMode = process.env.PLAYWRIGHT_SERVER_MODE ?? 'dev';",
    "const nextCli = 'node ./node_modules/next/dist/bin/next';",
    "const command = serverMode === 'start' ? `${nextCli} start --hostname 127.0.0.1 --port ${port}` : `${nextCli} dev --hostname 127.0.0.1 --port ${port}`;",
    '',
    'export default defineConfig({',
    "  testDir: './tests/e2e',",
    '  timeout: 60000,',
    '  workers: 1,',
    '  fullyParallel: false,',
    '  expect: {',
    '    timeout: 10000',
    '  },',
    '  use: {',
    "    baseURL: `http://127.0.0.1:${port}`,",
    "    trace: 'retain-on-failure'",
    '  },',
    '  webServer: {',
    '    command,',
    "    url: `http://127.0.0.1:${port}`,",
    '    timeout: 180000,',
    '    reuseExistingServer: false',
    '  },',
    '  projects: [',
    '    {',
    "      name: 'chromium',",
    "      use: { ...devices['Desktop Chrome'] }",
    '    },',
    '    {',
    "      name: 'mobile-chromium',",
    "      use: { ...devices['iPhone 13'] }",
    '    },',
    '    {',
    "      name: 'reduced-motion-chromium',",
    "      use: { ...devices['Desktop Chrome'] }",
    '    }',
    '  ]',
    '});',
    ''
  ].join('\n');
}

function globalsCssContent(designTokens) {
  const light = designTokens.theme.light.color;
  const dark = designTokens.theme.dark.color;
  const typography = designTokens.typography;
  const spacing = designTokens.spacing;
  const radii = designTokens.radii;
  const motion = designTokens.motion;
  const shadows = designTokens.shadows;

  return [
    '@tailwind base;',
    '@tailwind components;',
    '@tailwind utilities;',
    '',
    ':root {',
    `  --color-bg: ${light.surface};`,
    `  --color-fg: ${light.primary};`,
    `  --color-copy-muted: ${light.secondary};`,
    `  --color-copy-quiet: ${light.warning};`,
    `  --color-secondary: ${light.secondary};`,
    `  --color-accent: ${light.accent};`,
    '  --color-surface-strong: rgba(255, 255, 255, 0.86);',
    '  --color-surface-muted: rgba(255, 255, 255, 0.72);',
    '  --color-border: rgba(15, 23, 42, 0.12);',
    `  --radius-sm: ${radii.sm};`,
    `  --radius-md: ${radii.md};`,
    `  --radius-lg: ${radii.lg};`,
    `  --radius-pill: ${radii.pill};`,
    `  --space-section: ${spacing['2xl']};`,
    `  --shadow-sm: ${shadows.sm};`,
    `  --shadow-md: ${shadows.md};`,
    `  --shadow-lg: ${shadows.lg};`,
    `  --font-display: '${typography.fontFamilies.display}', 'Segoe UI', sans-serif;`,
    `  --font-body: '${typography.fontFamilies.body}', 'Segoe UI', sans-serif;`,
    `  --motion-fast: ${motion.duration.fast};`,
    `  --motion-base: ${motion.duration.base};`,
    `  --motion-slow: ${motion.duration.slow};`,
    `  --motion-ease: ${motion.easing.standard};`,
    `  --motion-emphasis: ${motion.easing.emphasis};`,
    '}',
    '',
    "[data-theme='dark'] {",
    `  --color-bg: ${dark.surface};`,
    `  --color-fg: ${dark.primary};`,
    `  --color-copy-muted: ${dark.secondary};`,
    `  --color-copy-quiet: ${dark.warning};`,
    `  --color-secondary: ${dark.secondary};`,
    `  --color-accent: ${dark.accent};`,
    '  --color-surface-strong: rgba(4, 21, 31, 0.84);',
    '  --color-surface-muted: rgba(15, 23, 42, 0.74);',
    '  --color-border: rgba(226, 232, 240, 0.16);',
    '}',
    '',
    'html {',
    '  color-scheme: light;',
    '}',
    '',
    "[data-theme='dark'] html,",
    "html[data-theme='dark'] {",
    '  color-scheme: dark;',
    '}',
    '',
    '* {',
    '  box-sizing: border-box;',
    '}',
    '',
    'body {',
    '  min-height: 100vh;',
    '  margin: 0;',
    '  color: var(--color-fg);',
    '  font-family: var(--font-body);',
    '  background-color: var(--color-bg);',
    '  background-image:',
    '    radial-gradient(circle at top left, rgba(15, 118, 110, 0.14), transparent 26%),',
    '    radial-gradient(circle at top right, rgba(249, 115, 22, 0.14), transparent 22%),',
    '    linear-gradient(180deg, rgba(255, 255, 255, 0.26) 0%, rgba(255, 255, 255, 0) 32%);',
    '}',
    '',
    '[data-motion="reduce"] *,',
    '[data-motion="reduce"] *::before,',
    '[data-motion="reduce"] *::after {',
    '  animation-duration: 0.01ms !important;',
    '  animation-iteration-count: 1 !important;',
    '  transition-duration: 0.01ms !important;',
    '  scroll-behavior: auto !important;',
    '}',
    '',
    '::selection {',
    '  background: rgba(15, 118, 110, 0.18);',
    '}',
    '',
    '.copy-muted {',
    '  color: var(--color-copy-muted);',
    '}',
    '',
    '.copy-quiet {',
    '  color: var(--color-copy-quiet);',
    '}',
    '',
    '.surface-card {',
    '  background: var(--color-surface-strong);',
    '  border: 1px solid var(--color-border);',
    '  box-shadow: var(--shadow-md);',
    '  backdrop-filter: blur(14px);',
    '}',
    '',
    '.surface-muted {',
    '  background: var(--color-surface-muted);',
    '  border: 1px solid var(--color-border);',
    '  backdrop-filter: blur(10px);',
    '}',
    '',
    '.primary-button {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 0.5rem;',
    '  border-radius: var(--radius-pill);',
    '  padding: 0.875rem 1.25rem;',
    '  background: var(--color-secondary);',
    '  color: white;',
    '  font-weight: 700;',
    '  text-decoration: none;',
    '  transition: transform var(--motion-base) var(--motion-emphasis), box-shadow var(--motion-base) var(--motion-ease);',
    '  box-shadow: var(--shadow-sm);',
    '}',
    '',
    '.primary-button:hover {',
    '  transform: translateY(-1px);',
    '  box-shadow: var(--shadow-md);',
    '}',
    '',
    '.secondary-button {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 0.5rem;',
    '  border-radius: var(--radius-pill);',
    '  padding: 0.875rem 1.25rem;',
    '  border: 1px solid var(--color-border);',
    '  color: var(--color-fg);',
    '  text-decoration: none;',
    '  background: transparent;',
    '  transition: background var(--motion-base) var(--motion-ease), transform var(--motion-base) var(--motion-ease);',
    '}',
    '',
    '.secondary-button:hover {',
    '  transform: translateY(-1px);',
    '  background: rgba(15, 23, 42, 0.04);',
    '}',
    '',
    '.focus-ring:focus-visible {',
    '  outline: 3px solid var(--color-accent);',
    '  outline-offset: 3px;',
    '}',
    '',
    '.hero-chip {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 0.5rem;',
    '  border-radius: var(--radius-pill);',
    '  border: 1px solid var(--color-border);',
    '  padding: 0.45rem 0.85rem;',
    '  background: var(--color-surface-muted);',
    '  font-size: 0.875rem;',
    '  letter-spacing: 0.02em;',
    '}',
    '',
    '.hero-halo {',
    '  position: relative;',
    '  overflow: hidden;',
    '}',
    '',
    '.hero-halo::after {',
    '  content: "";',
    '  position: absolute;',
    '  inset: -20% auto auto -10%;',
    '  width: 18rem;',
    '  height: 18rem;',
    '  border-radius: 9999px;',
    '  background: radial-gradient(circle, rgba(15, 118, 110, 0.18), transparent 62%);',
    '  pointer-events: none;',
    '}',
    '',
    '.trust-card {',
    '  background: var(--color-surface-muted);',
    '  border: 1px solid var(--color-border);',
    '}',
    '',
    '.status-pill {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 0.35rem;',
    '  padding: 0.45rem 0.75rem;',
    '  border-radius: var(--radius-pill);',
    '  border: 1px solid var(--color-border);',
    '  background: transparent;',
    '  color: var(--color-fg);',
    '}',
    '',
    '.status-pill[data-active="true"] {',
    '  background: var(--color-secondary);',
    '  color: white;',
    '}',
    '',
    '.route-frame {',
    '  padding-block: clamp(3rem, 6vw, 5rem);',
    '}',
    '',
    'h1, h2, h3, h4 {',
    '  font-family: var(--font-display);',
    '  letter-spacing: -0.03em;',
    '}',
    '',
    'a {',
    '  color: inherit;',
    '}',
    ''
  ].join('\n');
}

function siteContentFile(contentLibrary) {
  return [
    `export const siteContent = ${json(contentLibrary)} as const;`,
    '',
    'export type SiteContent = typeof siteContent;',
    ''
  ].join('\n');
}

function routeRegistryFile(routePlans, visualDifferentiationMap) {
  const routeRegistry = routePlans.map((plan) => ({
    path: plan.routeId,
    routeId: routeIdFromPath(plan.routeId),
    label: routeLabel(plan.routeId),
    navVisible: !plan.routeId.startsWith('/sign-') && plan.routeId !== '/terms' && plan.routeId !== '/privacy',
    public: !plan.routeId.startsWith('/sign-'),
    heroVariant: visualDifferentiationMap.find((entry) => entry.routeId === plan.routeId)?.heroVariant ?? 'signal-horizon'
  }));

  return [
    `export const routeRegistry = ${json(routeRegistry)} as const;`,
    '',
    'export const primaryNavigation = routeRegistry.filter((route) => route.navVisible);',
    'export const publicRoutes = routeRegistry.filter((route) => route.public);',
    "export const dynamicSurfaceStates = ['live', 'loading', 'error', 'empty', 'offline'] as const;",
    '',
    'export function heroVariantFor(pathname: string) {',
    "  return routeRegistry.find((route) => route.path === pathname)?.heroVariant ?? 'signal-horizon';",
    '}',
    ''
  ].join('\n');
}

function themeLibFile() {
  return [
    "export const THEME_STORAGE_KEY = 'ai-product-factory-theme';",
    '',
    "export type ThemeName = 'light' | 'dark';",
    '',
    'export function normalizeTheme(input: string | null | undefined): ThemeName {',
    "  return input === 'dark' ? 'dark' : 'light';",
    '}',
    '',
    'export function nextTheme(theme: ThemeName): ThemeName {',
    "  return theme === 'light' ? 'dark' : 'light';",
    '}',
    ''
  ].join('\n');
}

function appShellFile(projectName) {
  return [
    "'use client';",
    '',
    "import type { ReactNode } from 'react';",
    "import { AuthModalProvider } from './auth-modal';",
    "import { MobileBottomNav } from './mobile-bottom-nav';",
    "import { SiteFooter } from './site-footer';",
    "import { SiteHeader } from './site-header';",
    "import { ThemeProvider } from './theme-provider';",
    '',
    'type AppShellProps = {',
    '  children: ReactNode;',
    '};',
    '',
    'export function AppShell({ children }: AppShellProps) {',
    '  return (',
    '    <ThemeProvider>',
    '      <AuthModalProvider>',
    '        <a',
    "          href='#content'",
    "          className='focus-ring sr-only absolute left-4 top-4 z-50 rounded-pill bg-white px-4 py-2 text-sm font-semibold text-slate-900 focus:not-sr-only'",
    '        >',
    "          Skip to content",
    '        </a>',
    "        <div className='relative min-h-screen pb-28 md:pb-10'>",
    '          <SiteHeader />',
    "          <main id='content' className='mx-auto w-full max-w-7xl px-4 pb-16 pt-8 sm:px-6 lg:px-8'>",
    '            {children}',
    '          </main>',
    `          <SiteFooter projectName=${json(projectName)} />`,
    '          <MobileBottomNav />',
    '        </div>',
    '      </AuthModalProvider>',
    '    </ThemeProvider>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function themeProviderFile() {
  return [
    "'use client';",
    '',
    "import type { ReactNode } from 'react';",
    "import { createContext, useContext, useEffect, useMemo, useState } from 'react';",
    "import { THEME_STORAGE_KEY, nextTheme, normalizeTheme, type ThemeName } from '../lib/theme';",
    '',
    'type ThemeContextValue = {',
    '  theme: ThemeName;',
    '  mounted: boolean;',
    '  toggleTheme: () => void;',
    '};',
    '',
    'const ThemeContext = createContext<ThemeContextValue | null>(null);',
    '',
    'type ThemeProviderProps = {',
    '  children: ReactNode;',
    '};',
    '',
    'function applyTheme(theme: ThemeName) {',
    "  document.documentElement.setAttribute('data-theme', theme);",
    '}',
    '',
    'function bindMotionPreference() {',
    "  const media = window.matchMedia('(prefers-reduced-motion: reduce)');",
    '  const applyMotion = () => {',
    "    document.documentElement.setAttribute('data-motion', media.matches ? 'reduce' : 'full');",
    '  };',
    '  applyMotion();',
    '  if (typeof media.addEventListener === "function") {',
    "    media.addEventListener('change', applyMotion);",
    "    return () => media.removeEventListener('change', applyMotion);",
    '  }',
    "  media.addListener(applyMotion);",
    '  return () => media.removeListener(applyMotion);',
    '}',
    '',
    'export function ThemeProvider({ children }: ThemeProviderProps) {',
    "  const [theme, setTheme] = useState<ThemeName>('light');",
    '  const [mounted, setMounted] = useState(false);',
    '',
    '  useEffect(() => {',
    '    const storedTheme = normalizeTheme(window.localStorage.getItem(THEME_STORAGE_KEY));',
    '    setTheme(storedTheme);',
    '    applyTheme(storedTheme);',
    '    setMounted(true);',
    '    return bindMotionPreference();',
    '  }, []);',
    '',
    '  useEffect(() => {',
    '    if (!mounted) {',
    '      return;',
    '    }',
    '',
    '    applyTheme(theme);',
    '    window.localStorage.setItem(THEME_STORAGE_KEY, theme);',
    '  }, [mounted, theme]);',
    '',
    '  const value = useMemo(',
    '    () => ({',
    '      theme,',
    '      mounted,',
    '      toggleTheme: () => setTheme((currentTheme) => nextTheme(currentTheme))',
    '    }),',
    '    [mounted, theme]',
    '  );',
    '',
    '  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;',
    '}',
    '',
    'export function useTheme() {',
    '  const context = useContext(ThemeContext);',
    '  if (!context) {',
    "    throw new Error('useTheme must be used within ThemeProvider.');",
    '  }',
    '  return context;',
    '}',
    ''
  ].join('\n');
}

function themeSwitcherFile() {
  return [
    "'use client';",
    '',
    "import { useTheme } from './theme-provider';",
    '',
    'export function ThemeSwitcher() {',
    '  const { theme, mounted, toggleTheme } = useTheme();',
    "  const label = mounted ? `Theme: ${theme === 'light' ? 'Light' : 'Dark'}` : 'Theme';",
    '',
    '  return (',
    '    <button',
    "      type='button'",
    "      data-testid='theme-switcher'",
    "      aria-label='Toggle theme'",
    "      className='focus-ring secondary-button text-sm font-semibold'",
    '      onClick={toggleTheme}',
    '    >',
    '      {label}',
    '    </button>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function authModalFile() {
  return [
    "'use client';",
    '',
    "import Link from 'next/link';",
    "import type { ReactNode } from 'react';",
    "import { createContext, useContext, useEffect, useMemo, useState } from 'react';",
    '',
    "type AuthMode = 'sign-in' | 'sign-up';",
    '',
    'type AuthModalContextValue = {',
    '  isOpen: boolean;',
    '  mode: AuthMode;',
    '  open: (nextMode?: AuthMode) => void;',
    '  close: () => void;',
    '  switchMode: () => void;',
    '};',
    '',
    'const AuthModalContext = createContext<AuthModalContextValue | null>(null);',
    '',
    'type AuthModalProviderProps = {',
    '  children: ReactNode;',
    '};',
    '',
    'export function AuthModalProvider({ children }: AuthModalProviderProps) {',
    '  const [isOpen, setIsOpen] = useState(false);',
    "  const [mode, setMode] = useState<AuthMode>('sign-in');",
    '',
    '  useEffect(() => {',
    '    if (!isOpen) {',
    '      return undefined;',
    '    }',
    '',
    '    const handleEscape = (event: KeyboardEvent) => {',
    "      if (event.key === 'Escape') {",
    '        setIsOpen(false);',
    '      }',
    '    };',
    '',
    "    window.addEventListener('keydown', handleEscape);",
    "    return () => window.removeEventListener('keydown', handleEscape);",
    '  }, [isOpen]);',
    '',
    '  const value = useMemo(',
    '    () => ({',
    '      isOpen,',
    '      mode,',
    '      open: (nextMode: AuthMode = "sign-in") => {',
    '        setMode(nextMode);',
    '        setIsOpen(true);',
    '      },',
    '      close: () => setIsOpen(false),',
    '      switchMode: () => setMode((currentMode) => (currentMode === "sign-in" ? "sign-up" : "sign-in"))',
    '    }),',
    '    [isOpen, mode]',
    '  );',
    '',
    '  return (',
    '    <AuthModalContext.Provider value={value}>',
    '      {children}',
    '      <AuthModalRoot />',
    '    </AuthModalContext.Provider>',
    '  );',
    '}',
    '',
    'export function useAuthModal() {',
    '  const context = useContext(AuthModalContext);',
    '  if (!context) {',
    "    throw new Error('useAuthModal must be used within AuthModalProvider.');",
    '  }',
    '  return context;',
    '}',
    '',
    'function AuthModalRoot() {',
    '  const { isOpen, mode, close, switchMode } = useAuthModal();',
    '',
    '  if (!isOpen) {',
    '    return null;',
    '  }',
    '',
    "  const title = mode === 'sign-in' ? 'Sign in to the demo workspace' : 'Create a demo workspace';",
    "  const description = mode === 'sign-in' ? 'Use the modal for fast access or continue to the dedicated route.' : 'Switch modes here or continue to the dedicated route for a full-page flow.';",
    "  const routeHref = mode === 'sign-in' ? '/sign-in' : '/sign-up';",
    "  const switchLabel = mode === 'sign-in' ? 'Switch to sign up' : 'Switch to sign in';",
    '',
    '  return (',
    '    <div',
    "      data-testid='auth-modal-overlay'",
    "      className='fixed inset-0 z-50 flex items-center justify-center bg-slate-950/55 px-4 py-8'",
    '      onClick={close}',
    '    >',
    '      <div',
    "        role='dialog'",
    "        aria-modal='true'",
    "        aria-labelledby='auth-modal-title'",
    "        className='surface-card w-full max-w-lg rounded-hero p-6 text-left shadow-mellow sm:p-8'",
    '        onClick={(event) => event.stopPropagation()}',
    '      >',
    "        <div className='mb-6 flex items-start justify-between gap-4'>",
    '          <div>',
    "            <p className='hero-chip mb-3'>Modal-first auth entry</p>",
    "            <h2 id='auth-modal-title' className='text-2xl font-semibold text-ink'>{title}</h2>",
    "            <p className='mt-2 copy-muted'>{description}</p>",
    '          </div>',
    '          <button',
    "            type='button'",
    "            aria-label='Close auth modal'",
    "            className='focus-ring secondary-button px-3 py-2 text-sm'",
    '            onClick={close}',
    '          >',
    '            Close',
    '          </button>',
    '        </div>',
    "        <form className='grid gap-4'>",
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Email',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='email' placeholder='you@company.com' />",
    '          </label>',
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Password',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='password' placeholder='Enter a secure password' />",
    '          </label>',
    "          <div className='mt-2 flex flex-col gap-3 sm:flex-row'>",
    `            <button type='button' className='focus-ring primary-button'>${'Continue securely'}</button>`,
    '            <button type="button" className="focus-ring secondary-button" onClick={switchMode}>',
    '              {switchLabel}',
    '            </button>',
    '          </div>',
    "          <div className='copy-muted flex flex-wrap items-center gap-3 text-sm'>",
    '            <span>Need the full-page route instead?</span>',
    "            <Link className='focus-ring font-semibold underline-offset-4 hover:underline' href={routeHref}>",
    '              Open fallback route',
    '            </Link>',
    '          </div>',
    '        </form>',
    '      </div>',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function siteHeaderFile(projectName) {
  return [
    "'use client';",
    '',
    "import Link from 'next/link';",
    "import { usePathname } from 'next/navigation';",
    "import { ThemeSwitcher } from './theme-switcher';",
    "import { useAuthModal } from './auth-modal';",
    "import { primaryNavigation } from '../lib/route-registry';",
    "import { siteContent } from '../lib/site-content';",
    '',
    'export function SiteHeader() {',
    '  const pathname = usePathname();',
    '  const { open } = useAuthModal();',
    '  const brand = siteContent.brand;',
    '',
    '  return (',
    "    <header className='sticky top-0 z-40 border-b border-slate-200/60 bg-white/70 backdrop-blur dark:border-slate-700/40 dark:bg-slate-950/40'>",
    "      <div className='mx-auto flex w-full max-w-7xl items-center justify-between gap-4 px-4 py-4 sm:px-6 lg:px-8'>",
    "        <Link href='/' className='focus-ring flex items-center gap-3 rounded-pill px-2 py-1 text-sm font-semibold text-ink'>",
    "          <span className='inline-flex h-9 w-9 items-center justify-center rounded-full bg-accent text-sm font-black text-white'>AI</span>",
    `          <span className='font-semibold tracking-tight'>${projectName}</span>`,
    '        </Link>',
    "        <nav aria-label='Primary navigation' className='hidden items-center gap-2 md:flex'>",
    '          {primaryNavigation.map((item) => {',
    '            const isActive = pathname === item.path;',
    '            return (',
    '              <Link',
    '                key={item.path}',
    '                href={item.path}',
    '                aria-current={isActive ? "page" : undefined}',
    '                className={[',
    "                  'focus-ring rounded-pill px-4 py-2 text-sm font-medium transition',",
    "                  isActive ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900' : 'text-slate-700 hover:bg-white/70 dark:text-slate-200 dark:hover:bg-slate-800/70'",
    '                ].join(" ")}',
    '              >',
    '                {item.label}',
    '              </Link>',
    '            );',
    '          })}',
    '        </nav>',
    "        <div className='flex items-center gap-2 sm:gap-3'>",
    "          <a",
    "            href={brand.phoneHref}",
    "            className='focus-ring hidden rounded-pill border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-white/80 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800/80 lg:inline-flex'",
    "          >",
    "            Call",
    "          </a>",
    "          <a",
    "            href={brand.whatsAppHref}",
    "            target='_blank'",
    "            rel='noreferrer'",
    "            className='focus-ring hidden rounded-pill border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-white/80 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800/80 xl:inline-flex'",
    "          >",
    "            WhatsApp",
    "          </a>",
    '          <ThemeSwitcher />',
    '          <button',
    "            type='button'",
    "            aria-label='Open sign in modal'",
    "            className='focus-ring inline-flex rounded-pill border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-white/80 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800/80'",
    '            onClick={() => open("sign-in")}',
    '          >',
    '            Sign in',
    '          </button>',
    "          <Link href={brand.primaryCtaRoute} className='focus-ring primary-button hidden text-sm md:inline-flex'>",
    '            {brand.primaryCta}',
    '          </Link>',
    '        </div>',
    '      </div>',
    '    </header>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function siteFooterFile() {
  return [
    "import Link from 'next/link';",
    "import { primaryNavigation } from '../lib/route-registry';",
    "import { siteContent } from '../lib/site-content';",
    '',
    'type SiteFooterProps = {',
    '  projectName: string;',
    '};',
    '',
    'export function SiteFooter({ projectName }: SiteFooterProps) {',
    '  const footer = siteContent.footer;',
    '  const brand = siteContent.brand;',
    '  return (',
    "    <footer className='border-t border-slate-200/60 px-4 py-10 dark:border-slate-800/60 sm:px-6 lg:px-8'>",
    "      <div className='mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.2fr,0.9fr,0.9fr,0.9fr]'>",
    '        <div>',
    "          <p className='text-sm font-semibold uppercase tracking-[0.28em] copy-muted'>Built for production delivery</p>",
    "          <h2 className='mt-2 text-2xl font-semibold text-ink'>{projectName}</h2>",
    "          <p className='mt-3 max-w-2xl copy-muted'>{footer.attribution}</p>",
    "          <div className='mt-4 flex flex-wrap gap-2'>",
    "            <a href={brand.phoneHref} className='focus-ring rounded-pill border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-white/80 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800/80'>",
    '              {brand.phoneLabel}',
    '            </a>',
    "            <a href={brand.whatsAppHref} target='_blank' rel='noreferrer' className='focus-ring rounded-pill border border-slate-300 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-white/80 dark:border-slate-600 dark:text-slate-100 dark:hover:bg-slate-800/80'>",
    "              WhatsApp",
    '            </a>',
    '          </div>',
    '        </div>',
    "        <div className='grid gap-3'>",
    "          <p className='text-xs font-semibold uppercase tracking-[0.22em] copy-muted'>Navigation</p>",
    "          <nav aria-label='Footer navigation' className='grid gap-2 text-sm font-medium'>",
    '            {primaryNavigation.map((item) => (',
    '              <Link key={item.path} href={item.path} className="focus-ring rounded-pill px-3 py-2 hover:bg-white/70 dark:hover:bg-slate-800/70">',
    '                {item.label}',
    '              </Link>',
    '            ))}',
    '          </nav>',
    '        </div>',
    "        <div className='grid gap-3'>",
    "          <p className='text-xs font-semibold uppercase tracking-[0.22em] copy-muted'>Resources</p>",
    "          <ul className='grid gap-2 text-sm'>",
    '            {footer.columns.resources.map((item) => (',
    "              <li key={item} className='copy-muted'>",
    '                {item}',
    '              </li>',
    '            ))}',
    '          </ul>',
    '        </div>',
    "        <div className='grid gap-3'>",
    "          <p className='text-xs font-semibold uppercase tracking-[0.22em] copy-muted'>Contact</p>",
    "          <ul className='grid gap-2 text-sm'>",
    "            <li className='copy-muted'>{brand.supportEmail}</li>",
    "            <li className='copy-muted'>{brand.phoneLabel}</li>",
    "            <li>",
    "              <a href={brand.whatsAppHref} target='_blank' rel='noreferrer' className='focus-ring font-semibold text-emerald-700 underline-offset-4 hover:underline dark:text-emerald-300'>",
    "                Open WhatsApp",
    '              </a>',
    '            </li>',
    '          </ul>',
    '        </div>',
    '      </div>',
    '    </footer>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function mobileBottomNavFile() {
  return [
    "'use client';",
    '',
    "import Link from 'next/link';",
    "import { usePathname } from 'next/navigation';",
    "import { primaryNavigation } from '../lib/route-registry';",
    '',
    'const iconMap: Record<string, string> = {',
    "  Home: 'HM',",
    "  Product: 'PD',",
    "  Pricing: 'PR',",
    "  Services: 'SV',",
    "  About: 'AB',",
    "  Emergency: 'EM',",
    "  'Get Quote': 'QT',",
    "  Contact: 'CT'",
    '};',
    '',
    'export function MobileBottomNav() {',
    '  const pathname = usePathname();',
    '',
    '  return (',
    "    <nav",
    "      aria-label='Mobile bottom navigation'",
    "      data-testid='mobile-bottom-nav'",
    "      className='surface-card fixed bottom-4 left-1/2 z-40 flex w-[calc(100%-1.5rem)] max-w-xl -translate-x-1/2 items-center justify-between rounded-pill px-3 py-2 md:hidden'",
    '    >',
    '      {primaryNavigation.map((item) => {',
    '        const isActive = pathname === item.path;',
    '        const icon = iconMap[item.label] ?? item.label.slice(0, 2).toUpperCase();',
    '        return (',
    '          <Link',
    '            key={item.path}',
    '            href={item.path}',
    '            aria-current={isActive ? "page" : undefined}',
    '            className={[',
    "              'focus-ring flex min-w-[4.6rem] flex-col items-center gap-1 rounded-pill px-3 py-2 text-[0.7rem] font-semibold transition',",
    "              isActive ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900' : 'text-slate-700 dark:text-slate-100'",
    '            ].join(" ")}',
    '          >',
    '            <span className="text-[0.62rem] tracking-[0.18em]">{icon}</span>',
    '            <span>{item.label}</span>',
    '          </Link>',
    '        );',
    '      })}',
    '    </nav>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function routeHeroFile() {
  return [
    "import Link from 'next/link';",
    '',
    'type HeroStat = {',
    '  value: string;',
    '  label: string;',
    '};',
    '',
    'type HeroMedia = {',
    '  src: string;',
    '  alt: string;',
    '  badge?: string;',
    '};',
    '',
    'type RouteHeroProps = {',
    '  routeId: string;',
    '  variant: string;',
    '  eyebrow: string;',
    '  title: string;',
    '  description: string;',
    '  primaryCta?: string;',
    '  primaryHref?: string;',
    '  secondaryCta?: string;',
    '  secondaryHref?: string;',
    '  media?: HeroMedia;',
    '  stats?: readonly HeroStat[];',
    '};',
    '',
    'export function RouteHero({',
    '  routeId,',
    '  variant,',
    '  eyebrow,',
    '  title,',
    '  description,',
    '  primaryCta,',
    '  primaryHref,',
    '  secondaryCta,',
    '  secondaryHref,',
    '  media,',
    '  stats = []',
    '}: RouteHeroProps) {',
    '  return (',
    "    <section className='route-frame hero-halo grid gap-8 rounded-hero px-1 lg:grid-cols-[1.08fr,0.92fr] lg:items-stretch' data-hero-variant={variant}>",
    '      <div className="surface-card relative overflow-hidden rounded-hero px-6 py-8 sm:px-8 sm:py-10">',
    "        <p className='hero-chip mb-4'>{eyebrow}</p>",
    '        <div data-hero-route-id={routeId} className="grid gap-6">',
    "          <h1 className='max-w-4xl text-4xl font-semibold leading-tight text-ink sm:text-5xl lg:text-[3.6rem]'>",
    '            {title}',
    '          </h1>',
    "          <p className='max-w-2xl text-lg leading-8 copy-muted'>{description}</p>",
    '          <div className="flex flex-wrap items-center gap-3">',
    '            {primaryCta && primaryHref ? (',
    "              <Link className='focus-ring primary-button' data-primary-cta='true' href={primaryHref}>",
    '                {primaryCta}',
    '              </Link>',
    '            ) : null}',
    '            {secondaryCta && secondaryHref ? (',
    "              <Link className='focus-ring secondary-button' href={secondaryHref}>",
    '                {secondaryCta}',
    '              </Link>',
    '            ) : null}',
    '          </div>',
    '        </div>',
    '      </div>',
    "      <div className='grid gap-4'>",
    '        {media ? (',
    "          <figure className='surface-card relative overflow-hidden rounded-hero border border-slate-200/70 p-3 dark:border-slate-700/70'>",
    "            <img src={media.src} alt={media.alt} className='h-64 w-full rounded-soft object-cover sm:h-72 lg:h-[21rem]' loading='lazy' />",
    '            {media.badge ? (',
    "              <figcaption className='absolute left-6 top-6 hero-chip bg-white/85 dark:bg-slate-900/80'>",
    '                {media.badge}',
    '              </figcaption>',
    '            ) : null}',
    '          </figure>',
    '        ) : null}',
    "        <div className='grid gap-3 sm:grid-cols-3 lg:grid-cols-1'>",
    '          {stats.length > 0 ? (',
    '            stats.map((stat) => (',
    "              <div key={stat.label} className='surface-muted rounded-hero p-5'>",
    "                <p className='text-3xl font-semibold text-ink'>{stat.value}</p>",
    "                <p className='mt-2 text-sm leading-6 copy-muted'>{stat.label}</p>",
    '              </div>',
    '            ))',
    '          ) : (',
    "            <div className='surface-muted rounded-hero p-6 sm:col-span-3 lg:col-span-1'>",
    "              <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Why this route exists</p>",
    "              <p className='mt-3 text-base leading-7 copy-muted'>Each public route keeps a distinct hero variant and intent so the app never collapses into a single generic wrapper.</p>",
    '            </div>',
    '          )}',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function sectionPrimitivesFile() {
  return [
    "import Link from 'next/link';",
    '',
    'type FeatureItem = {',
    '  title: string;',
    '  body: string;',
    '};',
    '',
    'type ProofContent = {',
    '  quote?: string;',
    '  speaker?: string;',
    '  outcomes: readonly string[];',
    '};',
    '',
    'type PricingPlan = {',
    '  name: string;',
    '  price: string;',
    '  cadence: string;',
    '  summary: string;',
    '  features: readonly string[];',
    '};',
    '',
    'type ContactChannel = {',
    '  title: string;',
    '  detail: string;',
    '  action: string;',
    '};',
    '',
    'type FaqItem = {',
    '  question: string;',
    '  answer: string;',
    '};',
    '',
    'export function TrustStrip({ proofStatement, logos }: { proofStatement: string; logos: readonly string[] }) {',
    '  return (',
    "    <section className='route-frame grid gap-4'>",
    "      <div className='surface-card rounded-hero px-6 py-5 sm:px-8'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>Immediate trust</p>",
    "        <div className='mt-4 grid gap-4 lg:grid-cols-[1.4fr,1fr] lg:items-center'>",
    "          <p data-testid='trust-strip-card' className='text-base leading-7 text-ink'>{proofStatement}</p>",
    "          <div className='grid grid-cols-2 gap-3 sm:grid-cols-4'>",
    '            {logos.map((logo) => (',
    "              <div key={logo} className='trust-card rounded-soft px-4 py-3 text-center text-sm font-semibold text-ink'>",
    '                {logo}',
    '              </div>',
    '            ))}',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function FeatureGrid({ title, items }: { title: string; items: readonly FeatureItem[] }) {',
    '  return (',
    "    <section className='route-frame grid gap-6'>",
    "      <div className='flex flex-col gap-3'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>Capability map</p>",
    "        <h2 className='text-3xl font-semibold text-ink sm:text-4xl'>{title}</h2>",
    '      </div>',
    "      <div className='grid gap-4 md:grid-cols-3'>",
    '        {items.map((item) => (',
    "          <article key={item.title} className='surface-card rounded-hero p-6'>",
    "            <h3 className='text-xl font-semibold text-ink'>{item.title}</h3>",
    "            <p className='mt-3 text-base leading-7 copy-muted'>{item.body}</p>",
    '          </article>',
    '        ))}',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function WorkflowTimeline({ title, steps }: { title: string; steps: readonly string[] }) {',
    '  return (',
    "    <section className='route-frame grid gap-6 lg:grid-cols-[0.65fr,1fr]'>",
    '      <div>',
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>Workflow</p>",
    "        <h2 className='mt-3 text-3xl font-semibold text-ink sm:text-4xl'>{title}</h2>",
    '      </div>',
    "      <ol className='grid gap-4'>",
    '        {steps.map((step, index) => (',
    "          <li key={step} className='surface-card rounded-hero p-5'>",
    "            <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Step {index + 1}</p>",
    "            <p className='mt-3 text-base leading-7 text-ink'>{step}</p>",
    '          </li>',
    '        ))}',
    '      </ol>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function ProofPanel({ proof }: { proof: ProofContent }) {',
    '  return (',
    "    <section className='route-frame grid gap-6 lg:grid-cols-[1.05fr,0.95fr]'>",
    "      <article className='surface-card rounded-hero p-6 sm:p-8'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>Proof surface</p>",
    '        {proof.quote ? (',
    "          <blockquote className='mt-4 text-2xl font-semibold leading-tight text-ink sm:text-3xl'>“{proof.quote}”</blockquote>",
    '        ) : null}',
    '        {proof.speaker ? <p className="mt-4 copy-muted">{proof.speaker}</p> : null}',
    '      </article>',
    "      <div className='grid gap-3'>",
    '        {proof.outcomes.map((outcome) => (',
    "          <div key={outcome} className='surface-muted rounded-soft px-5 py-4 text-base text-ink'>",
    '            {outcome}',
    '          </div>',
    '        ))}',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function FaqList({ items }: { items: readonly FaqItem[] }) {',
    '  return (',
    "    <section className='route-frame grid gap-6'>",
    "      <div className='flex flex-col gap-3'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>FAQs</p>",
    "        <h2 className='text-3xl font-semibold text-ink sm:text-4xl'>Questions handled before they become blockers</h2>",
    '      </div>',
    "      <div className='grid gap-3'>",
    '        {items.map((item) => (',
    "          <details key={item.question} className='surface-card rounded-soft p-5'>",
    "            <summary className='cursor-pointer list-none text-lg font-semibold text-ink'>{item.question}</summary>",
    "            <p className='mt-3 text-base leading-7 copy-muted'>{item.answer}</p>",
    '          </details>',
    '        ))}',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function PricingGrid({ plans }: { plans: readonly PricingPlan[] }) {',
    '  return (',
    "    <section className='route-frame grid gap-6'>",
    "      <div className='flex flex-col gap-3'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.26em] copy-muted'>Commercial paths</p>",
    "        <h2 className='text-3xl font-semibold text-ink sm:text-4xl'>Choose the right operating depth</h2>",
    '      </div>',
    "      <div className='grid gap-4 lg:grid-cols-3'>",
    '        {plans.map((plan, index) => (',
    '          <article',
    '            key={plan.name}',
    "            data-conversion-surface={index === 1 ? 'primary' : undefined}",
    '            className={[',
    "              'surface-card rounded-hero p-6',",
    "              index === 1 ? 'border-2 border-emerald-500' : ''",
    '            ].join(" ")}',
    '          >',
    "            <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>{plan.name}</p>",
    "            <div className='mt-4 flex items-end gap-2'>",
    "              <p className='text-4xl font-semibold text-ink'>{plan.price}</p>",
    "              <p className='copy-muted'>{plan.cadence}</p>",
    '            </div>',
    "            <p className='mt-4 text-base leading-7 copy-muted'>{plan.summary}</p>",
    "            <ul className='mt-6 grid gap-3 text-sm leading-6 text-ink'>",
    '              {plan.features.map((feature) => (',
    "                <li key={feature} className='surface-muted rounded-soft px-4 py-3'>",
    '                  {feature}',
    '                </li>',
    '              ))}',
    '            </ul>',
    '          </article>',
    '        ))}',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function ContactGrid({ channels, supportWindow, sla }: { channels: readonly ContactChannel[]; supportWindow: string; sla: string }) {',
    '  return (',
    "    <section className='route-frame grid gap-6 lg:grid-cols-[1fr,0.85fr]'>",
    "      <div data-testid='contact-channel-grid' className='grid gap-4'>",
    '        {channels.map((channel) => (',
    "          <article key={channel.title} className='surface-card rounded-hero p-6'>",
    "            <h2 className='text-xl font-semibold text-ink'>{channel.title}</h2>",
    "            <p className='mt-3 text-base leading-7 copy-muted'>{channel.detail}</p>",
    "            <a className='focus-ring mt-4 inline-flex font-semibold text-emerald-700 underline-offset-4 hover:underline dark:text-emerald-300' href={channel.action.startsWith('http') ? channel.action : channel.action.startsWith('+') ? `tel:${channel.action.replace(/[^+\\d]/g, '')}` : `mailto:${channel.action}`}>",
    '              {channel.action}',
    '            </a>',
    '          </article>',
    '        ))}',
    '      </div>',
    "      <div className='surface-card rounded-hero p-6 sm:p-8'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Service standards</p>",
    "        <p className='mt-4 text-base leading-7 text-ink'>{supportWindow}</p>",
    "        <p className='mt-3 text-base leading-7 copy-muted'>{sla}</p>",
    "        <form className='mt-6 grid gap-4'>",
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Your name',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='text' placeholder='Alex Morgan' />",
    '          </label>',
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Work email',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='email' placeholder='alex@company.com' />",
    '          </label>',
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            How can we help?',
    "            <textarea className='focus-ring min-h-32 rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' placeholder='Share the brief, failing gate, or delivery blocker.' />",
    '          </label>',
    "          <button type='button' className='focus-ring primary-button justify-self-start'>Send request</button>",
    '        </form>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function ConversionBand({ title, body, href, cta }: { title: string; body?: string; href: string; cta: string }) {',
    '  return (',
    "    <section className='route-frame'>",
    "      <div className='surface-card rounded-hero px-6 py-8 sm:px-8 sm:py-10'>",
    "        <div className='grid gap-6 lg:grid-cols-[1fr,auto] lg:items-center'>",
    '          <div>',
    "            <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Conversion</p>",
    "            <h2 className='mt-3 max-w-3xl text-3xl font-semibold text-ink sm:text-4xl'>{title}</h2>",
    '            {body ? <p className="mt-4 max-w-2xl text-base leading-7 copy-muted">{body}</p> : null}',
    '          </div>',
    "          <Link href={href} className='focus-ring primary-button justify-self-start lg:justify-self-end'>",
    '            {cta}',
    '          </Link>',
    '        </div>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    '',
    'export function AuthCard({ title, description, actionLabel, switchHref, switchLabel }: { title: string; description: string; actionLabel: string; switchHref: string; switchLabel: string }) {',
    '  return (',
    "    <section className='route-frame flex justify-center'>",
    "      <div className='surface-card w-full max-w-xl rounded-hero p-6 sm:p-8'>",
    "        <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Fallback auth route</p>",
    "        <h1 className='mt-4 text-3xl font-semibold text-ink sm:text-4xl'>{title}</h1>",
    "        <p className='mt-3 text-base leading-7 copy-muted'>{description}</p>",
    "        <form className='mt-8 grid gap-4'>",
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Email',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='email' placeholder='you@company.com' />",
    '          </label>',
    "          <label className='grid gap-2 text-sm font-medium text-ink'>",
    '            Password',
    "            <input className='focus-ring rounded-soft border border-slate-300 bg-white/80 px-4 py-3 text-slate-900' type='password' placeholder='••••••••' />",
    '          </label>',
    "          <button type='button' className='focus-ring primary-button justify-self-start'>",
    '            {actionLabel}',
    '          </button>',
    "          <Link href={switchHref} className='focus-ring text-sm font-semibold text-emerald-700 underline-offset-4 hover:underline dark:text-emerald-300'>",
    '            {switchLabel}',
    '          </Link>',
    '        </form>',
    '      </div>',
    '    </section>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function liveStatusPanelFile() {
  return [
    "'use client';",
    '',
    "import { useState } from 'react';",
    '',
    'type StateEntry = {',
    '  id: string;',
    '  title: string;',
    '  description: string;',
    '};',
    '',
    'type LiveStatusPanelProps = {',
    '  states: readonly StateEntry[];',
    '};',
    '',
    'export function LiveStatusPanel({ states }: LiveStatusPanelProps) {',
    '  const [activeId, setActiveId] = useState(states[0]?.id ?? "live");',
    '  const activeState = states.find((state) => state.id === activeId) ?? states[0];',
    '',
    '  return (',
    "    <section data-testid='live-status-panel' className='surface-card rounded-hero p-6 sm:p-8'>",
    "      <p className='text-sm font-semibold uppercase tracking-[0.24em] copy-muted'>Dynamic surface states</p>",
    "      <div className='mt-5 flex flex-wrap gap-2'>",
    '        {states.map((state) => (',
    '          <button',
    '            key={state.id}',
    "            type='button'",
    '            data-active={state.id === activeId}',
    "            className='focus-ring status-pill text-sm font-semibold'",
    '            onClick={() => setActiveId(state.id)}',
    '          >',
    '            {state.title}',
    '          </button>',
    '        ))}',
    '      </div>',
    '      {activeState ? (',
    "        <div className='mt-6 rounded-hero border border-dashed border-slate-300 px-5 py-6 dark:border-slate-700'>",
    "          <p className='text-2xl font-semibold text-ink'>{activeState.title}</p>",
    "          <p className='mt-3 text-base leading-7 copy-muted'>{activeState.description}</p>",
    '        </div>',
    '      ) : null}',
    '    </section>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function layoutFile(projectName, summary) {
  return [
    "import type { Metadata } from 'next';",
    "import './globals.css';",
    "import { AppShell } from '../components/app-shell';",
    '',
    'export const metadata: Metadata = {',
    `  title: ${json(projectName)},`,
    `  description: ${json(summary)}`,
    '};',
    '',
    'type RootLayoutProps = {',
    '  children: React.ReactNode;',
    '};',
    '',
    'export default function RootLayout({ children }: RootLayoutProps) {',
    '  return (',
    "    <html lang='en' data-theme='light' data-motion='full' suppressHydrationWarning>",
    '      <body>',
    '        <AppShell>{children}</AppShell>',
    '      </body>',
    '    </html>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function homePageFile() {
  return [
    "import { RouteHero } from '../components/route-hero';",
    "import { ConversionBand, FeatureGrid, FaqList, ProofPanel, TrustStrip, WorkflowTimeline } from '../components/section-primitives';",
    "import { heroVariantFor } from '../lib/route-registry';",
    "import { siteContent } from '../lib/site-content';",
    '',
    'export default function HomePage() {',
    '  const content = siteContent.home;',
    '',
    '  return (',
    "    <div data-route-id='home'>",
    '      <RouteHero',
    "        routeId='home'",
    "        variant={heroVariantFor('/')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        secondaryCta={content.hero.secondaryCta}',
    '        secondaryHref={content.hero.secondaryHref}',
    '        media={content.hero.media}',
    '        stats={content.hero.stats}',
    '      />',
    '      <TrustStrip proofStatement={content.trust.proofStatement} logos={content.trust.logos} />',
    "      <FeatureGrid title='What this system keeps under control' items={content.features} />",
    "      <WorkflowTimeline title='The execution path' steps={content.workflow} />",
    '      <ProofPanel proof={content.proof} />',
    '      <FaqList items={content.faq} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        body={content.cta.body}',
    '        href={content.hero.primaryHref}',
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function productPageFile() {
  return [
    "import { LiveStatusPanel } from '../../components/live-status-panel';",
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, FeatureGrid, ProofPanel, WorkflowTimeline } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function ProductPage() {',
    '  const content = siteContent.product;',
    '',
    '  return (',
    "    <div data-route-id='product'>",
    '      <RouteHero',
    "        routeId='product'",
    "        variant={heroVariantFor('/product')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        media={content.hero.media}',
    '      />',
    "      <FeatureGrid title='Capability pillars that survive real use' items={content.pillars} />",
    "      <div className='route-frame grid gap-6 lg:grid-cols-[0.72fr,1fr] lg:items-start'>",
    "        <WorkflowTimeline title='How the product route handles runtime complexity' steps={content.workflow} />",
    '        <LiveStatusPanel states={content.states} />',
    '      </div>',
    '      <ProofPanel proof={content.proof} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        href={content.hero.primaryHref}',
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function pricingPageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, FaqList, PricingGrid, ProofPanel } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function PricingPage() {',
    '  const content = siteContent.pricing;',
    '',
    '  return (',
    "    <div data-route-id='pricing'>",
    '      <RouteHero',
    "        routeId='pricing'",
    "        variant={heroVariantFor('/pricing')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        media={content.hero.media}',
    '      />',
    '      <PricingGrid plans={content.plans} />',
    '      <ProofPanel proof={content.proof} />',
    '      <FaqList items={content.faq} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    "        href='/contact'",
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function contactPageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ContactGrid, ConversionBand, WorkflowTimeline } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function ContactPage() {',
    '  const content = siteContent.contact;',
    '',
    '  return (',
    "    <div data-route-id='contact'>",
    '      <RouteHero',
    "        routeId='contact'",
    "        variant={heroVariantFor('/contact')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        secondaryCta={content.hero.secondaryCta}',
    '        secondaryHref={content.hero.secondaryHref}',
    '        media={content.hero.media}',
    '      />',
    '      <ContactGrid channels={content.channels} supportWindow={content.supportWindow} sla={content.sla} />',
    "      <WorkflowTimeline title='How support requests are handled' steps={content.workflow} />",
    '      <ConversionBand',
    "        title='Need the architecture walkthrough before a formal engagement?'",
    "        body='Share the locked brief and the factory can respond against a known route inventory and quality bar.'",
    '        href={content.hero.primaryHref}',
    '        cta={content.hero.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function servicesPageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, FaqList, FeatureGrid, ProofPanel } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function ServicesPage() {',
    '  const content = siteContent.services;',
    '',
    '  return (',
    "    <div data-route-id='services'>",
    '      <RouteHero',
    "        routeId='services'",
    "        variant={heroVariantFor('/services')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        secondaryCta={content.hero.secondaryCta}',
    '        secondaryHref={content.hero.secondaryHref}',
    '        media={content.hero.media}',
    '      />',
    "      <FeatureGrid title='Core service coverage' items={content.features} />",
    '      <ProofPanel proof={content.proof} />',
    '      <FaqList items={content.faq} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        body={content.cta.body}',
    "        href='/quote'",
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function aboutPageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, ProofPanel, TrustStrip } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function AboutPage() {',
    '  const content = siteContent.about;',
    '',
    '  return (',
    "    <div data-route-id='about'>",
    '      <RouteHero',
    "        routeId='about'",
    "        variant={heroVariantFor('/about')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        media={content.hero.media}',
    '      />',
    '      <TrustStrip proofStatement={content.trust.proofStatement} logos={content.trust.logos} />',
    '      <ProofPanel proof={content.proof} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        body={content.cta.body}',
    "        href='/quote'",
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function emergencyPageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, TrustStrip, WorkflowTimeline } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function EmergencyPage() {',
    '  const content = siteContent.emergency;',
    '',
    '  return (',
    "    <div data-route-id='emergency'>",
    '      <RouteHero',
    "        routeId='emergency'",
    "        variant={heroVariantFor('/emergency')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        secondaryCta={content.hero.secondaryCta}',
    '        secondaryHref={content.hero.secondaryHref}',
    '        media={content.hero.media}',
    '      />',
    '      <TrustStrip proofStatement={content.trust.proofStatement} logos={content.trust.logos} />',
    "      <WorkflowTimeline title='Emergency response flow' steps={content.workflow} />",
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        body={content.cta.body}',
    '        href={content.hero.primaryHref}',
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function quotePageFile() {
  return [
    "import { RouteHero } from '../../components/route-hero';",
    "import { ConversionBand, FaqList, WorkflowTimeline } from '../../components/section-primitives';",
    "import { heroVariantFor } from '../../lib/route-registry';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function QuotePage() {',
    '  const content = siteContent.quote;',
    '',
    '  return (',
    "    <div data-route-id='quote'>",
    '      <RouteHero',
    "        routeId='quote'",
    "        variant={heroVariantFor('/quote')}",
    '        eyebrow={content.hero.eyebrow}',
    '        title={content.hero.title}',
    '        description={content.hero.description}',
    '        primaryCta={content.hero.primaryCta}',
    '        primaryHref={content.hero.primaryHref}',
    '        media={content.hero.media}',
    '      />',
    "      <WorkflowTimeline title='Quote request workflow' steps={content.workflow} />",
    '      <FaqList items={content.faq} />',
    '      <ConversionBand',
    '        title={content.cta.title}',
    '        body={content.cta.body}',
    "        href='/contact'",
    '        cta={content.cta.primaryCta}',
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function termsPageFile() {
  return [
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function TermsPage() {',
    '  const content = siteContent.legal.terms;',
    '',
    '  return (',
    "    <article data-route-id='terms' className='route-frame grid gap-8'>",
    "      <header className='surface-card rounded-hero p-6 sm:p-8'>",
    "        <p className='hero-chip mb-3'>Legal</p>",
    "        <h1 className='text-3xl font-semibold text-ink'>{content.title}</h1>",
    "        <p className='mt-3 copy-muted'>{content.intro}</p>",
    '      </header>',
    "      <section className='grid gap-4'>",
    '        {content.sections.map((entry) => (',
    "          <div key={entry.heading} className='surface-card rounded-soft p-5'>",
    "            <h2 className='text-xl font-semibold text-ink'>{entry.heading}</h2>",
    "            <p className='mt-2 copy-muted'>{entry.body}</p>",
    '          </div>',
    '        ))}',
    '      </section>',
    '    </article>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function privacyPageFile() {
  return [
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function PrivacyPage() {',
    '  const content = siteContent.legal.privacy;',
    '',
    '  return (',
    "    <article data-route-id='privacy' className='route-frame grid gap-8'>",
    "      <header className='surface-card rounded-hero p-6 sm:p-8'>",
    "        <p className='hero-chip mb-3'>Legal</p>",
    "        <h1 className='text-3xl font-semibold text-ink'>{content.title}</h1>",
    "        <p className='mt-3 copy-muted'>{content.intro}</p>",
    '      </header>',
    "      <section className='grid gap-4'>",
    '        {content.sections.map((entry) => (',
    "          <div key={entry.heading} className='surface-card rounded-soft p-5'>",
    "            <h2 className='text-xl font-semibold text-ink'>{entry.heading}</h2>",
    "            <p className='mt-2 copy-muted'>{entry.body}</p>",
    '          </div>',
    '        ))}',
    '      </section>',
    '    </article>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function signInPageFile() {
  return [
    "import { AuthCard } from '../../components/section-primitives';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function SignInPage() {',
    '  return (',
    "    <div data-route-id='sign-in'>",
    '      <AuthCard',
    '        title={siteContent.auth.signIn.title}',
    '        description={siteContent.auth.signIn.description}',
    "        actionLabel='Sign in'",
    "        switchHref='/sign-up'",
    "        switchLabel='Need an account? Open sign up'",
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function signUpPageFile() {
  return [
    "import { AuthCard } from '../../components/section-primitives';",
    "import { siteContent } from '../../lib/site-content';",
    '',
    'export default function SignUpPage() {',
    '  return (',
    "    <div data-route-id='sign-up'>",
    '      <AuthCard',
    '        title={siteContent.auth.signUp.title}',
    '        description={siteContent.auth.signUp.description}',
    "        actionLabel='Create account'",
    "        switchHref='/sign-in'",
    "        switchLabel='Already have access? Open sign in'",
    '      />',
    '    </div>',
    '  );',
    '}',
    ''
  ].join('\n');
}

function runtimeDetectScriptFile() {
  return [
    "import { existsSync, readFileSync } from 'node:fs';",
    '',
    "const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));",
    '',
    'if (!packageJson.name.startsWith("generated-")) {',
    "  throw new Error('Generated app runtime detection failed: unexpected package name.');",
    '}',
    '',
    "const requiredPaths = ['src/app', 'src/components', '.factory-meta/build-plan.json'];",
    '',
    'for (const relativePath of requiredPaths) {',
    '  if (!existsSync(new URL(`../${relativePath}`, import.meta.url))) {',
    '    throw new Error(`Generated app runtime detection failed: missing ${relativePath}`);',
    '  }',
    '}',
    '',
    "console.log('Generated app runtime root detected.');",
    ''
  ].join('\n');
}

function dependencyCheckScriptFile() {
  return [
    "import { createRequire } from 'node:module';",
    "import { existsSync } from 'node:fs';",
    '',
    'const require = createRequire(import.meta.url);',
    "const requiredModules = ['next/package.json', 'react/package.json', 'react-dom/package.json', '@playwright/test/package.json'];",
    '',
    "if (!existsSync(new URL('../node_modules', import.meta.url))) {",
    "  throw new Error('Dependencies are not installed. Run npm install before release:check.');",
    '}',
    '',
    'for (const modulePath of requiredModules) {',
    '  require.resolve(modulePath);',
    '}',
    '',
    "console.log('Generated app dependency validation passed.');",
    ''
  ].join('\n');
}

function runPlaywrightScriptFile() {
  return [
    "import { spawnSync } from 'node:child_process';",
    '',
    'const suite = process.argv[2];',
    'const specMap = {',
    "  smoke: 'tests/e2e/smoke.spec.ts',",
    "  a11y: 'tests/e2e/a11y.spec.ts',",
    "  full: 'tests/e2e/full.spec.ts'",
    '};',
    '',
    'if (!suite || !specMap[suite]) {',
    "  throw new Error('Expected a test suite name: smoke, a11y, or full.');",
    '}',
    '',
    'const env = {',
    '  ...process.env,',
    "  PLAYWRIGHT_SERVER_MODE: suite === 'full' ? 'start' : 'dev'",
    '};',
    '',
    "const result = spawnSync('npx', ['playwright', 'test', specMap[suite], '--config=playwright.config.ts', '--reporter=line'], {",
    '  stdio: "inherit",',
    '  env,',
    '  shell: process.platform === "win32"',
    '});',
    '',
    'if (result.error) {',
    '  throw result.error;',
    '}',
    '',
    'process.exit(result.status ?? 1);',
    ''
  ].join('\n');
}

function lintScriptFile() {
  return [
    "import { readdirSync, readFileSync, statSync } from 'node:fs';",
    "import path from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");',
    "const scanRoots = ['src', 'tests'];",
    'const failures = [];',
    '',
    'function scanDirectory(directory) {',
    '  for (const entry of readdirSync(directory)) {',
    '    const fullPath = path.join(directory, entry);',
    '    const stats = statSync(fullPath);',
    '    if (stats.isDirectory()) {',
    '      scanDirectory(fullPath);',
    '      continue;',
    '    }',
    '    if (!/\.(ts|tsx|mjs|md)$/.test(fullPath)) {',
    '      continue;',
    '    }',
    '    const contents = readFileSync(fullPath, "utf8");',
    '    if (/TODO|FIXME/.test(contents)) {',
    '      failures.push(`Lint gate failed: unresolved marker in ${path.relative(rootDir, fullPath)}`);',
    '    }',
    '  }',
    '}',
    '',
    'for (const relativePath of scanRoots) {',
    '  scanDirectory(path.join(rootDir, relativePath));',
    '}',
    '',
    "const requiredFiles = ['src/components/theme-switcher.tsx', 'src/components/mobile-bottom-nav.tsx', 'src/components/auth-modal.tsx'];",
    'for (const relativePath of requiredFiles) {',
    '  const fullPath = path.join(rootDir, relativePath);',
    '  try {',
    '    statSync(fullPath);',
    '  } catch {',
    '    failures.push(`Lint gate failed: missing required file ${relativePath}`);',
    '  }',
    '}',
    '',
    'if (failures.length > 0) {',
    '  throw new Error(failures.join("\\n"));',
    '}',
    '',
    "console.log('Custom lint gate passed with zero warnings tolerated.');",
    ''
  ].join('\n');
}

function auditScriptFile(routePlans, visualDifferentiationMap, buildPlan) {
  const expectedRoutes = routePlans.map((plan) => plan.routeId);
  const expectedComponents = buildPlan.components;

  return [
    "import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';",
    "import path from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");',
    `const expectedRoutes = ${json(expectedRoutes)};`,
    `const expectedHeroVariants = ${json(visualDifferentiationMap)};`,
    `const expectedComponents = ${json(expectedComponents)};`,
    'const failures = [];',
    'const evidence = [];',
    '',
    'function routePathToFile(routePath) {',
    "  if (routePath === '/') {",
    "    return 'src/app/page.tsx';",
    '  }',
    "  return `src/app${routePath}/page.tsx`;",
    '}',
    '',
    'for (const routePath of expectedRoutes) {',
    '  const relativePath = routePathToFile(routePath);',
    '  const fullPath = path.join(rootDir, relativePath);',
    '  if (!existsSync(fullPath)) {',
    '    failures.push(`Missing route file: ${relativePath}`);',
    '    continue;',
    '  }',
    '  const contents = readFileSync(fullPath, "utf8");',
    '  const routeId = routePath === "/" ? "home" : routePath.replace(/^\\//, "").replace(/\\//g, "-");',
    "  if (!contents.includes(`data-route-id='${routeId}'`) && !contents.includes(`data-route-id=\"${routeId}\"`)) {",
    '    failures.push(`Route marker missing in ${relativePath}`);',
    '  }',
    '  evidence.push(`route:${routePath} -> ${relativePath}`);',
    '}',
    '',
    'const routeRegistryPath = path.join(rootDir, "src/lib/route-registry.ts");',
    'if (!existsSync(routeRegistryPath)) {',
    '  failures.push("Missing route registry: src/lib/route-registry.ts");',
    '} else {',
    '  const routeRegistryContents = readFileSync(routeRegistryPath, "utf8");',
    '  for (const entry of expectedHeroVariants) {',
    '    if (!routeRegistryContents.includes(entry.heroVariant)) {',
    '      failures.push(`Hero variant ${entry.heroVariant} not referenced in src/lib/route-registry.ts`);',
    '    }',
    '  }',
    '  evidence.push("route-registry -> src/lib/route-registry.ts");',
    '}',
    '',
    'for (const componentName of expectedComponents) {',
    '  const fileName = componentName',
    "    .replace(/([a-z])([A-Z])/g, '$1-$2')",
    '    .toLowerCase();',
    '  const relativePath = `src/components/${fileName}.tsx`;',
    '  if (!existsSync(path.join(rootDir, relativePath))) {',
    '    failures.push(`Missing component file: ${relativePath}`);',
    '  } else {',
    '    evidence.push(`component:${componentName} -> ${relativePath}`);',
    '  }',
    '}',
    '',
    'const report = {',
    '  status: failures.length === 0 ? "passed" : "failed",',
    '  failures,',
    '  evidence',
    '};',
    '',
    'mkdirSync(path.join(rootDir, "reports"), { recursive: true });',
    'writeFileSync(path.join(rootDir, "reports", "frontend-self-audit.json"), JSON.stringify(report, null, 2));',
    '',
    'if (failures.length > 0) {',
    '  throw new Error(failures.join("\\n"));',
    '}',
    '',
    "console.log('Frontend self-audit passed and evidence was written to reports/frontend-self-audit.json.');",
    ''
  ].join('\n');
}

function runbookFile(projectName) {
  return [
    '# Generated Runbook',
    '',
    `Project: ${projectName}`,
    '',
    '## Working Directory',
    '',
    'Run all commands from this generated app root.',
    '',
    '## Install Dependencies',
    '',
    '```bash',
    'npm install',
    'npx playwright install chromium',
    '```',
    '',
    '## Primary Commands',
    '',
    '```bash',
    'npm run runtime:detect',
    'npm run dependency:check',
    'npm run lint',
    'npm run typecheck',
    'npm run test:unit',
    'npm run test:a11y',
    'npm run e2e:smoke',
    'npm run build',
    'npm run e2e:full',
    'npm run audit:frontend',
    'npm run release:check',
    '```',
    '',
    '## Production Gate Order',
    '',
    '1. runtime-root detection',
    '2. dependency validation',
    '3. zero-warning lint gate',
    '4. typecheck',
    '5. unit tests',
    '6. accessibility smoke tests',
    '7. Playwright smoke on desktop, mobile, and reduced motion',
    '8. production build',
    '9. full post-build E2E against the started server',
    '10. frontend self-audit evidence generation',
    ''
  ].join('\n');
}

function unitTestFile() {
  return [
    "import { describe, expect, it } from 'vitest';",
    "import { dynamicSurfaceStates, publicRoutes } from '../../src/lib/route-registry';",
    "import { nextTheme, normalizeTheme } from '../../src/lib/theme';",
    '',
    "describe('generated content contracts', () => {",
    "  it('keeps unique hero variants across public routes', () => {",
    '    const heroVariants = publicRoutes.map((route) => route.heroVariant);',
    '    expect(new Set(heroVariants).size).toBe(heroVariants.length);',
    '  });',
    '',
    "  it('declares all required dynamic states', () => {",
    "    expect(dynamicSurfaceStates).toEqual(['live', 'loading', 'error', 'empty', 'offline']);",
    '  });',
    '',
    "  it('normalizes theme selection deterministically', () => {",
    "    expect(normalizeTheme(undefined)).toBe('light');",
    "    expect(normalizeTheme('dark')).toBe('dark');",
    "    expect(nextTheme('light')).toBe('dark');",
    '  });',
    '});',
    ''
  ].join('\n');
}

function smokeTestFile(routePlans) {
  const publicRoutes = routePlans
    .map((plan) => plan.routeId)
    .filter((path) => !path.startsWith('/sign-'));
  const desktopTarget = publicRoutes.find((path) => path !== '/' && path !== '/terms' && path !== '/privacy') ?? '/contact';
  const desktopTargetLabel = routeLabel(desktopTarget);
  const desktopTargetId = routeIdFromPath(desktopTarget);
  const mobileTarget = publicRoutes.find((path) => path !== '/') ?? '/';
  const mobileTargetLabel = routeLabel(mobileTarget);
  const conversionRoute = publicRoutes.includes('/quote')
    ? '/quote'
    : (publicRoutes.includes('/pricing') ? '/pricing' : desktopTarget);
  const conversionId = routeIdFromPath(conversionRoute);
  const routeHealthChecks = [...new Set([desktopTarget, conversionRoute, publicRoutes.includes('/contact') ? '/contact' : desktopTarget])];

  return [
    "import { expect, test } from '@playwright/test';",
    '',
    "test('home route renders without console or hydration errors', async ({ page }) => {",
    '  const errors: string[] = [];',
    '  page.on("console", (message) => {',
    '    if (message.type() === "error") {',
    '      errors.push(message.text());',
    '    }',
    '  });',
    '  page.on("pageerror", (error) => errors.push(error.message));',
    '',
    "  await page.goto('/');",
    '  await expect(page.locator(`[data-route-id="home"]`)).toBeVisible();',
    '  expect(errors).toEqual([]);',
    '});',
    '',
    "test('primary navigation works on desktop and mobile', async ({ page }, testInfo) => {",
    "  await page.goto('/');",
    '  if (testInfo.project.name === "mobile-chromium") {',
    `    await page.getByTestId('mobile-bottom-nav').getByRole('link', { name: ${json(mobileTargetLabel)} }).click();`,
    '  } else {',
    `    await page.getByRole('link', { name: ${json(desktopTargetLabel)} }).first().click();`,
    '  }',
    `  await expect(page).toHaveURL(new RegExp(${json(`${desktopTarget}$`)}));`,
    `  await expect(page.locator(${json(`[data-route-id="${desktopTargetId}"]`)})).toBeVisible();`,
    '});',
    '',
    "test('ThemeSwitcher changes theme and persists preference', async ({ page }) => {",
    "  await page.goto('/');",
    "  await page.getByTestId('theme-switcher').click();",
    "  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');",
    '  await page.reload();',
    "  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');",
    '});',
    '',
    "test('MobileBottomNav renders on mobile breakpoints and routes correctly', async ({ page }, testInfo) => {",
    "  await page.goto('/');",
    "  const nav = page.getByTestId('mobile-bottom-nav');",
    '  if (testInfo.project.name === "mobile-chromium") {',
    '    await expect(nav).toBeVisible();',
    `    await nav.getByRole('link', { name: ${json(mobileTargetLabel)} }).click();`,
    `    await expect(page).toHaveURL(new RegExp(${json(`${mobileTarget}$`)}));`,
    '  } else {',
    '    await expect(nav).not.toBeVisible();',
    '  }',
    '});',
    '',
    "test('AuthModal opens, switches mode, closes, and fallback auth routes resolve', async ({ page }) => {",
    "  await page.goto('/');",
    "  await page.getByRole('button', { name: 'Open sign in modal' }).click();",
    "  const dialog = page.getByRole('dialog');",
    '  await expect(dialog).toBeVisible();',
    "  await page.getByRole('button', { name: 'Switch to sign up' }).click();",
    "  await expect(dialog).toContainText('Create a demo workspace');",
    "  await page.getByRole('button', { name: 'Close auth modal' }).click();",
    '  await expect(dialog).toBeHidden();',
    "  await page.goto('/sign-in');",
    '  await expect(page.locator(`[data-route-id="sign-in"]`)).toBeVisible();',
    "  await page.goto('/sign-up');",
    '  await expect(page.locator(`[data-route-id="sign-up"]`)).toBeVisible();',
    '});',
    '',
    "test('primary conversion surface is reachable in two interactions or less from home', async ({ page }) => {",
    "  await page.goto('/');",
    '  await page.locator(`[data-primary-cta="true"]`).first().click();',
    `  await expect(page).toHaveURL(new RegExp(${json(`${conversionRoute}$`)}));`,
    `  await expect(page.locator(${json(`[data-route-id="${conversionId}"]`)})).toBeVisible();`,
    '});',
    '',
    "test('content, conversion, and contact routes resolve with healthy app responses', async ({ page }) => {",
    `  for (const route of ${json(routeHealthChecks)}) {`,
    '    const response = await page.goto(route);',
    '    expect(response?.ok()).toBeTruthy();',
    '  }',
    '});',
    ''
  ].join('\n');
}

function a11yTestFile(routePlans) {
  const publicRoutes = routePlans
    .map((plan) => plan.routeId)
    .filter((path) => !path.startsWith('/sign-') && path !== '/terms' && path !== '/privacy');
  const secondaryRoute = publicRoutes.find((path) => path !== '/') ?? '/';

  return [
    "import AxeBuilder from '@axe-core/playwright';",
    "import { expect, test } from '@playwright/test';",
    '',
    `for (const route of ${json([...new Set(['/', secondaryRoute])])}) {`,
    "  const label = route === '/' ? 'home' : route.replace(/^\//, '').replace(/-/g, '_');",
    "  test(`${label} route has no serious or critical accessibility violations`, async ({ page }) => {",
    '    await page.goto(route);',
    '    const results = await new AxeBuilder({ page }).analyze();',
    '    const blockingViolations = results.violations.filter((violation) => ["serious", "critical"].includes(violation.impact ?? ""));',
    '    expect(blockingViolations, JSON.stringify(blockingViolations, null, 2)).toHaveLength(0);',
    '  });',
    '}',
    ''
  ].join('\n');
}

function fullTestFile(routePlans) {
  const publicRoutes = routePlans
    .map((plan) => plan.routeId)
    .filter((path) => !path.startsWith('/sign-') && path !== '/terms' && path !== '/privacy');
  const heroRoutes = publicRoutes.slice(0, 4);
  const dynamicStateRoute = publicRoutes.includes('/product') ? '/product' : null;

  const lines = [
    "import { expect, test } from '@playwright/test';",
    '',
    "test('public routes keep differentiated hero variants', async ({ page }) => {",
    '  const variants = new Set<string>();',
    `  for (const route of ${json(heroRoutes)}) {`,
    '    await page.goto(route);',
    '    const variant = await page.locator("[data-hero-variant]").first().getAttribute("data-hero-variant");',
    '    expect(variant).toBeTruthy();',
    '    variants.add(String(variant));',
    '  }',
    `  expect(variants.size).toBe(${Math.max(1, heroRoutes.length)});`,
    '});',
    '',
    "test('reduced motion project sets the reduced motion marker', async ({ page }, testInfo) => {",
    "  test.skip(testInfo.project.name !== 'reduced-motion-chromium');",
    "  await page.emulateMedia({ reducedMotion: 'reduce' });",
    "  await page.goto('/');",
    "  await expect(page.locator('html')).toHaveAttribute('data-motion', 'reduce');",
    '});',
    '',
    "test('keyboard navigation exposes a visible focus ring', async ({ page }, testInfo) => {",
    "  test.skip(testInfo.project.name === 'mobile-chromium');",
    "  await page.goto('/');",
    "  await page.locator('body').focus();",
    "  await page.keyboard.press('Tab');",
    "  const skipLink = page.getByRole('link', { name: 'Skip to content' });",
    '  await expect(skipLink).toBeFocused();',
    "  await expect(skipLink).toHaveCSS('outline-style', 'solid');",
    '});',
    '',
    "test('dark theme keeps trust-critical surfaces visually distinct', async ({ page }) => {",
    "  await page.goto('/');",
    "  await page.getByTestId('theme-switcher').click();",
    "  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');",
    "  const trustCard = page.getByTestId('trust-strip-card');",
    '  const colors = await trustCard.evaluate((element) => {',
    '    const styles = window.getComputedStyle(element);',
    '    return { background: styles.backgroundColor, color: styles.color };',
    '  });',
    '  expect(colors.background).not.toBe(colors.color);',
    '});'
  ];

  if (dynamicStateRoute) {
    lines.push(
      '',
      "test('dynamic product states cover loading, error, empty, and offline paths', async ({ page }) => {",
      `  await page.goto(${json(dynamicStateRoute)});`,
      "  for (const title of ['Awaiting source handoff', 'Source adapter mismatch', 'No signal yet', 'Offline continuity', 'Live signal sync']) {",
      "    await page.getByRole('button', { name: title }).click();",
      "    await expect(page.getByTestId('live-status-panel')).toContainText(title);",
      '  }',
      '});'
    );
  }

  lines.push('');
  return lines.join('\n');
}

function gitignoreFile() {
  return ['node_modules/', '.next/', 'playwright-report/', 'test-results/', 'reports/frontend-self-audit.json', ''].join('\n');
}

function publicGitkeepFile() {
  return '';
}

function nextEnvFile() {
  return "/// <reference types='next' />\n/// <reference types='next/image-types/global' />\n\n// This file is managed by Next.js.\n";
}

function stylesDeclarationFile() {
  return "declare module '*.css';\n";
}

export async function buildFrontendApp({ appRoot, brief, designTokens, composition, buildPlan }) {
  const plannedRouteSet = new Set(composition.routePlans.map((plan) => plan.routeId));

  const files = {
    '.gitignore': gitignoreFile(),
    'package.json': packageJsonContent(buildPlan),
    'tsconfig.json': tsconfigContent(),
    'next.config.mjs': nextConfigContent(),
    'postcss.config.mjs': postcssConfigContent(),
    'tailwind.config.mjs': tailwindConfigContent(),
    'vitest.config.mjs': vitestConfigContent(),
    'playwright.config.ts': playwrightConfigContent(3005),
    'next-env.d.ts': nextEnvFile(),
    'src/types/styles.d.ts': stylesDeclarationFile(),
    'RUN.generated.md': runbookFile(brief.projectName),
    'public/.gitkeep': publicGitkeepFile(),
    '.factory-meta/build-plan.json': `${json(buildPlan)}\n`,
    '.factory-meta/visual-differentiation-map.json': `${json(composition.visualDifferentiationMap)}\n`,
    '.factory-meta/frontend-summary.json': `${json(composition.frontendSummary)}\n`,
    'scripts/runtime-detect.mjs': runtimeDetectScriptFile(),
    'scripts/dependency-check.mjs': dependencyCheckScriptFile(),
    'scripts/run-playwright.mjs': runPlaywrightScriptFile(),
    'scripts/lint.mjs': lintScriptFile(),
    'scripts/audit-frontend.mjs': auditScriptFile(composition.routePlans, composition.visualDifferentiationMap, buildPlan),
    'src/app/globals.css': globalsCssContent(designTokens),
    'src/app/layout.tsx': layoutFile(brief.projectName, brief.summary),
    'src/app/page.tsx': homePageFile(),
    'src/components/app-shell.tsx': appShellFile(brief.projectName),
    'src/components/theme-provider.tsx': themeProviderFile(),
    'src/components/theme-switcher.tsx': themeSwitcherFile(),
    'src/components/auth-modal.tsx': authModalFile(),
    'src/components/site-header.tsx': siteHeaderFile(brief.projectName),
    'src/components/site-footer.tsx': siteFooterFile(),
    'src/components/mobile-bottom-nav.tsx': mobileBottomNavFile(),
    'src/components/route-hero.tsx': routeHeroFile(),
    'src/components/section-primitives.tsx': sectionPrimitivesFile(),
    'src/components/live-status-panel.tsx': liveStatusPanelFile(),
    'src/lib/site-content.ts': siteContentFile(composition.contentLibrary),
    'src/lib/route-registry.ts': routeRegistryFile(composition.routePlans, composition.visualDifferentiationMap),
    'src/lib/theme.ts': themeLibFile(),
    'tests/unit/site-content.test.ts': unitTestFile(),
    'tests/e2e/smoke.spec.ts': smokeTestFile(composition.routePlans),
    'tests/e2e/a11y.spec.ts': a11yTestFile(composition.routePlans),
    'tests/e2e/full.spec.ts': fullTestFile(composition.routePlans)
  };

  if (plannedRouteSet.has('/product')) {
    files['src/app/product/page.tsx'] = productPageFile();
  }

  if (plannedRouteSet.has('/pricing')) {
    files['src/app/pricing/page.tsx'] = pricingPageFile();
  }

  if (plannedRouteSet.has('/services')) {
    files['src/app/services/page.tsx'] = servicesPageFile();
  }

  if (plannedRouteSet.has('/about')) {
    files['src/app/about/page.tsx'] = aboutPageFile();
  }

  if (plannedRouteSet.has('/emergency')) {
    files['src/app/emergency/page.tsx'] = emergencyPageFile();
  }

  if (plannedRouteSet.has('/quote')) {
    files['src/app/quote/page.tsx'] = quotePageFile();
  }

  if (plannedRouteSet.has('/contact')) {
    files['src/app/contact/page.tsx'] = contactPageFile();
  }

  if (plannedRouteSet.has('/terms')) {
    files['src/app/terms/page.tsx'] = termsPageFile();
  }

  if (plannedRouteSet.has('/privacy')) {
    files['src/app/privacy/page.tsx'] = privacyPageFile();
  }

  if (plannedRouteSet.has('/sign-in')) {
    files['src/app/sign-in/page.tsx'] = signInPageFile();
  }

  if (plannedRouteSet.has('/sign-up')) {
    files['src/app/sign-up/page.tsx'] = signUpPageFile();
  }

  for (const [relativePath, content] of Object.entries(files)) {
    await writeGeneratedFile(appRoot, relativePath, content);
  }

  return {
    fileCount: Object.keys(files).length,
    relativeFiles: Object.keys(files)
  };
}
