/**
 * Content library — English (US)
 * Single source of truth for all visible strings.
 * No inline strings may appear in JSX; use the t() helper from @/lib/content.
 */

const content = {
  nav: {
    home: 'Home',
    services: 'Services',
    portfolio: 'Portfolio',
    testimonials: 'Reviews',
    blog: 'Blog',
    quote: 'Get a Quote',
    contact: 'Contact',
    sign_in: 'Sign In',
    account: 'My Account',
    about: 'About',
  },
  cta: {
    get_quote: 'Get Instant Quote',
    book_call: 'Request a Call',
    open_whatsapp: 'Message on WhatsApp',
    open_ai_assistant: 'Ask Solar Assistant',
    view_projects: 'View Projects',
    learn_more: 'Learn More',
    read_more: 'Read More',
    see_all: 'See All',
    back: 'Back',
    submit: 'Submit',
    close: 'Close',
  },
  support: {
    phone_label: 'Call us',
    whatsapp_label: 'WhatsApp',
    email_label: 'Email us',
    hours_label: 'Business hours',
  },
  home: {
    hero: {
      eyebrow: 'Solar systems tailored to your property',
      title: 'Switch to clean energy with confidence',
      subtitle:
        'Explore savings, compare system options, and get a tailored proposal — all without leaving your home.',
      primary_cta: 'Start Instant Quote',
      secondary_cta: 'View Projects',
    },
    trust: {
      license: 'Licensed & insured installer',
      warranty: '25-year system warranty',
      installations: '500+ completed installations',
    },
    services_title: 'Everything your solar project needs',
    services_subtitle: 'From the first site visit to commissioning and long-term monitoring.',
    portfolio_title: 'Recent installations',
    portfolio_subtitle: 'Real projects, real performance outcomes across residential and commercial.',
    testimonials_title: 'What our customers say',
    stats: {
      installs_value: '500+',
      installs_label: 'Completed installations',
      warranty_value: '25 years',
      warranty_label: 'Performance warranty',
      rating_value: '4.9/5',
      rating_label: 'Verified customer rating',
    },
    featured_case: {
      eyebrow: 'Featured case study',
      title: 'From high bills to predictable savings in 90 days',
      body: 'A Newcastle household upgraded to a hybrid solar + battery setup and reached an average bill reduction of 78% in the first quarter.',
      metric_1: '13.2 kW system + battery',
      metric_2: 'Estimated payback: 4.1 years',
      cta: 'Read the full case study',
    },
    cta_title: 'Ready to start saving?',
    cta_subtitle: 'Get your instant estimate in under 3 minutes.',
    cta_primary: 'Get Instant Quote',
    cta_secondary: 'Talk to an expert',
  },
  services: {
    hero: {
      eyebrow: 'Our services',
      title: 'Solar solutions from assessment to activation',
      subtitle: 'Every installation is engineered for maximum output and long-term reliability.',
      primary_cta: 'Get Instant Quote',
    },
    trust_chips: {
      certified: 'Certified installers',
      warranty: '25-yr workmanship warranty',
      response: '24-hr service response',
    },
    categories_title: 'What we install',
    process_title: 'How it works',
    financing_title: 'Financing & warranty',
    financing_banner: {
      title: 'Flexible payment paths, long-term protection',
      body: 'Choose low-upfront financing options while keeping full visibility on performance and warranty coverage from day one.',
      point_1: 'Low-upfront financing options',
      point_2: '25-year performance warranty',
      point_3: 'Dedicated local support team',
    },
    warranty_title: 'Our warranty promise',
    testimonials_slice_title: 'Customers love the results',
    cta_title: 'Get your free site assessment',
    cta_subtitle: 'Our engineers will evaluate your roof, shading, and usage profile.',
  },
  portfolio: {
    hero: {
      eyebrow: 'Our work',
      title: 'Real projects, real performance outcomes',
      subtitle: 'Residential and commercial installations across the region.',
    },
    filter_all: 'All projects',
    filter_residential: 'Residential',
    filter_commercial: 'Commercial',
    filter_monitoring: 'Monitoring',
    empty_state: 'No projects found for this filter.',
    cta_title: 'Ready to start your project?',
    cta_subtitle: 'Get a tailored proposal for your property.',
  },
  about: {
    hero: {
      eyebrow: 'Our story',
      title: 'Clean energy built on trust and craftsmanship',
      subtitle: 'Over a decade of installations, innovations, and satisfied customers.',
      year_badge: 'Est. 2012',
    },
    mission: {
      title: 'Our mission',
      body: 'We believe clean energy should be accessible, affordable, and built to last. Every system we design is engineered for the specific needs of your property — not templated.',
    },
    values: {
      title: 'What we stand for',
      quality: { title: 'Quality', body: 'Tier-1 panels and components only.' },
      integrity: { title: 'Integrity', body: 'No hidden fees, ever.' },
      sustainability: { title: 'Sustainability', body: 'Clean energy for a better future.' },
      innovation: { title: 'Innovation', body: '10+ years of leading-edge installations.' },
      transparency: { title: 'Transparency', body: 'No hidden fees, ever.' },
      expertise: { title: 'Expertise', body: '10+ years of proven installations.' },
      community: { title: 'Community', body: 'Local team, local impact.' },
      quality_title: 'Quality',
      quality_body: 'Tier-1 panels and components only.',
      integrity_title: 'Integrity',
      integrity_body: 'No hidden fees, ever.',
      sustainability_title: 'Sustainability',
      sustainability_body: 'Clean energy for a better future.',
      innovation_title: 'Innovation',
      innovation_body: '10+ years of leading-edge installations.',
    },
    team: {
      title: 'Meet the team',
      subtitle: 'Certified engineers and project managers dedicated to your installation.',
    },
    certifications_title: 'Certifications & affiliations',
    certifications: {
      title: 'Certifications & affiliations',
      cec: 'CEC Accredited Installer',
      nsw: 'NSW Licensed Electrical Contractor',
      edge: 'SolarEdge Installation Partner',
      enphase: 'Enphase Certified Installer',
    },
    cta_title: 'Work with us',
    cta_subtitle: 'We\'re always looking for skilled tradespeople and engineers.',
  },
  testimonials: {
    hero: {
      eyebrow: 'Customer reviews',
      title: 'Trusted by hundreds of homeowners and businesses',
      subtitle: 'Read what our customers say about their solar experience.',
      aggregate_rating: '4.9',
      aggregate_count: '248 verified reviews',
      aggregate_source: 'Google · Facebook · Trustpilot',
    },
    list: {
      title: 'All reviews',
    },
    highlights: {
      title: 'What customers value most',
      speed_title: 'Fast project turnaround',
      speed_body: 'From site check to commissioning with clear milestones and proactive updates.',
      quality_title: 'Clean, high-quality installs',
      quality_body: 'Neat cabling, premium components, and compliance-first workmanship.',
      support_title: 'Support that stays responsive',
      support_body: 'Dedicated local support for maintenance, monitoring, and warranty needs.',
    },
    cta: {
      title: 'Join our satisfied customers',
      subtitle: 'Get your instant quote and see what solar savings look like for your property.',
    },
  },
  blog: {
    hero: {
      eyebrow: 'Solar insights',
      title: 'Guides, news, and real project stories',
      featured_label: 'Featured',
      subtitle: 'Industry news, practical guides, and real project stories from the SolarPro team.',
    },
    list_title: 'Recent articles',
    categories: {
      all: 'All',
      guides: 'Guides',
      news: 'Industry news',
      projects: 'Project stories',
      savings: 'Savings & finance',
    },
    pillars: {
      title: 'Explore by focus area',
      guides: 'Buyer guides and practical checklists',
      projects: 'Installation stories and outcomes',
      savings: 'Tariffs, rebates, and ROI breakdowns',
    },
    read_time: 'min read',
    share: 'Share',
    back_to_blog: 'Back to blog',
    related_title: 'Related articles',
    cta_title: 'Ready to switch to solar?',
    cta_subtitle: 'Get your instant estimate in under 3 minutes.',
  },
  contact: {
    hero: {
      eyebrow: 'Get in touch',
      title: 'We\'re ready to help',
      subtitle: 'Choose the channel that works best for you.',
    },
    response_promise: {
      title: 'What happens after you contact us',
      step_1: 'A specialist responds and validates your goals',
      step_2: 'We map your property constraints and options',
      step_3: 'You receive clear next steps with no pressure',
    },
    channels: {
      phone: {
        label: 'Call us',
        detail: 'Mon – Fri, 7 am – 6 pm',
        cta: 'Call now',
      },
      whatsapp: {
        label: 'WhatsApp',
        detail: 'Typically replies within 1 hour',
        cta: 'Open WhatsApp',
      },
      email: {
        label: 'Email',
        detail: 'Response within 1 business day',
        cta: 'Send email',
      },
      assistant: {
        label: 'Solar AI Assistant',
        detail: 'Instant answers about sizing and savings',
        cta: 'Ask the assistant',
      },
      phone_label: 'Call us',
      phone_value: '+61 2 9999 0000',
      phone_hours: 'Mon – Fri, 7 am – 6 pm',
      whatsapp_label: 'WhatsApp',
      whatsapp_value: 'Message on WhatsApp',
      whatsapp_raw: '61299990000',
      whatsapp_response: 'Typically replies within 1 hour',
      email_label: 'Email us',
      email_value: 'hello@solarpro.example.com',
      email_response: 'Response within 1 business day',
      assistant_label: 'Solar AI Assistant',
      assistant_value: 'Ask the assistant',
      assistant_sublabel: 'Instant answers about sizing and savings',
    },
    address: {
      title: 'Office & service area',
      line1: 'SolarPro Installations',
      line2: '42 Renewable Way',
      city: 'Greenville NSW 2000',
    },
    hours: {
      title: 'Business hours',
      mon_fri_label: 'Monday – Friday',
      mon_fri_value: '7:00 am – 6:00 pm',
      sat_label: 'Saturday',
      sat_value: '8:00 am – 1:00 pm',
      sun_label: 'Sunday',
      sun_value: 'Closed',
    },
    address_title: 'Office & service area',
    hours_title: 'Business hours',
    cta_title: 'Prefer a scheduled call?',
    cta_subtitle: 'Book a 15-minute call with a solar specialist.',
  },
  quote: {
    hero: {
      eyebrow: 'Free instant estimate',
      title: 'Estimate your solar fit in minutes',
      subtitle: 'Use the instant calculator, then submit for a personalised proposal.',
    },
    step1: 'Your details',
    step2: 'Request proposal',
    step3: 'All done',
    calculator_label: 'Solar savings calculator',
    calculator: {
      title: 'Step 1: Your usage & property',
      bill_label: 'Average monthly electricity bill',
      bill_placeholder: '$ 0',
      roof_label: 'Roof type',
      roof_options: {
        tile: 'Tile',
        metal: 'Metal / Colorbond',
        flat: 'Flat / Membrane',
        other: 'Other',
      },
      size_label: 'Estimated system size',
      output_title: 'Your estimate',
      output_system_size: 'System size',
      output_savings: 'Est. annual savings',
      output_payback: 'Payback period',
      cta: 'Proceed to proposal request',
    },
    form: {
      title: 'Step 2: Request your proposal',
      name_label: 'Full name',
      name_placeholder: 'Jane Smith',
      email_label: 'Email address',
      email_placeholder: 'jane@example.com',
      phone_label: 'Phone number',
      phone_placeholder: '+61 4xx xxx xxx',
      address_label: 'Property address',
      address_placeholder: '123 Solar St, Suburb',
      submit: 'Send proposal request',
      submitting: 'Sending…',
      privacy_note: 'Your details are used only to prepare your quote.',
    },
    success: {
      title: 'Your quote request is in progress',
      subtitle: 'We\'ll review your details and send a personalised proposal within 1 business day.',
      cta: 'Back to home',
    },
    error: {
      general: 'Something went wrong. Please try again or call us directly.',
    },
  },
  auth: {
    no_account: "Don't have an account?",
    create_account: 'Create account',
    have_account: 'Already have an account?',
    sign_in: 'Sign in',
    trust_rating: 'Average rating',
    trust_installs: 'Installations completed',
    trust_warranty: 'Workmanship warranty',
    sign_in_form: {
      title: 'Welcome back',
      subtitle: 'Sign in to view your proposals and system monitoring.',
      email_label: 'Email address',
      password_label: 'Password',
      forgot_password: 'Forgot password?',
      submit: 'Sign in',
      no_account: "Don't have an account?",
      register_link: 'Create account',
    },
    sign_up_form: {
      title: 'Create your solar account',
      subtitle: 'Track your proposals, system performance, and service history.',
      name_label: 'Full name',
      email_label: 'Email address',
      password_label: 'Password',
      password_hint: 'Minimum 8 characters',
      submit: 'Create account',
      value_strip: {
        proposals: 'Track your proposals',
        monitoring: 'Live system monitoring',
        support: '24/7 priority support',
      },
      have_account: 'Already have an account?',
      sign_in_link: 'Sign in',
    },
  },
  account: {
    title: 'My account',
    proposals_tab: 'Proposals',
    monitoring_tab: 'Monitoring',
    profile_tab: 'Profile',
    no_proposals: 'No proposals yet.',
    request_proposal: 'Request a proposal',
    welcome_eyebrow: 'My account',
    welcome_title: 'Welcome back',
    start_new_quote: 'Start a new quote',
    panel: {
      quote_title: 'My proposals',
      quote_sub: 'View and track your quote requests.',
      install_title: 'My installation',
      install_sub: 'Installation timeline and status updates.',
      monitoring_title: 'System monitoring',
      monitoring_sub: 'Real-time energy production data.',
      docs_title: 'Documents',
      docs_sub: 'Certificates, warranties, and permits.',
    },
  },
  assistant: {
    modal: {
      title: 'Solar Assistant',
      subtitle: 'Ask about system sizing, savings assumptions, and next steps.',
    },
    input: {
      placeholder: 'Ask a question about your project…',
    },
    thinking: 'Thinking…',
    error: 'The assistant encountered an error. Please try again.',
  },
  footer: {
    company_name: 'SolarPro Installations',
    license_number: 'Lic. ELEC-XXXX',
    address: '42 Renewable Way, Greenville NSW 2000',
    hours: 'Mon–Fri 7 am – 6 pm, Sat 8 am – 1 pm',
    copyright: '© {year} SolarPro Installations. All rights reserved.',
    nav_services: 'Services',
    nav_portfolio: 'Portfolio',
    nav_about: 'About',
    nav_blog: 'Blog',
    nav_contact: 'Contact',
    legal_privacy: 'Privacy Policy',
    legal_terms: 'Terms of Service',
    social_instagram: 'Instagram',
    social_facebook: 'Facebook',
    social_linkedin: 'LinkedIn',
  },
  legal: {
    privacy: {
      title: 'Privacy Policy',
      last_updated: 'Last updated: January 2025',
      intro: 'SolarPro Installations ("we", "us", "our") is committed to protecting your personal information in accordance with the Privacy Act 1988 (Cth).',
      collection_title: 'Information we collect',
      collection_body: 'We collect your name, email address, phone number, and property address when you request a quote or contact us. We may also collect usage data through cookies.',
      use_title: 'How we use your information',
      use_body: 'We use your information to provide installation services, send you quotes and service updates, and improve our business. We do not sell your personal information.',
      contact_title: 'Contact us',
      contact_body: 'For privacy enquiries, contact our Privacy Officer at privacy@solarpro.example.com.',
    },
    terms: {
      title: 'Terms of Service',
      last_updated: 'Last updated: January 2025',
      intro: 'By using the SolarPro Installations website or services, you agree to these terms of service.',
      services_title: 'Our services',
      services_body: 'We provide solar system design, supply, installation, and monitoring services for residential and commercial properties in NSW.',
      liability_title: 'Limitation of liability',
      liability_body: 'Our liability is limited to the value of the services provided. We are not liable for consequential or indirect losses.',
      contact_title: 'Contact',
      contact_body: 'For questions about these terms, contact us at legal@solarpro.example.com.',
    },
  },
  utility: {
    not_found: {
      title: 'Page not found',
      subtitle: 'The page you\'re looking for doesn\'t exist or has been moved.',
      cta: 'Back to home',
    },
    error: {
      title: 'Something went wrong',
      subtitle: 'We\'re working on it. Please try refreshing the page.',
      retry: 'Try again',
    },
    loading: 'Loading…',
  },
} as const

export default content
export type ContentTree = typeof content
