export const siteContent = {
  "meta.siteName": "Summit Ridge Roofing",
  "meta.siteDescription": "High-trust roofing inspections, repairs, and replacements with rapid storm response.",
  "nav.home": "Home",
  "nav.services": "Services",
  "nav.materials": "Materials",
  "nav.projects": "Projects",
  "nav.financing": "Financing",
  "nav.contact": "Contact",
  "nav.faq": "FAQ",
  "nav.about": "About",
  "nav.areas": "Areas",
  "nav.signIn": "Sign In",
  "nav.signUp": "Get Started",
  "hero.home.headline": "Trusted Roofing Solutions For Your Home",
  "hero.home.subheading": "Inspection-first roofing for homeowners who want clarity, speed, and reliable workmanship.",
  "hero.home.ctaPrimary": "Schedule Inspection",
  "hero.home.ctaSecondary": "View Projects",
  "hero.storm.headline": "Storm Damage? We Can Inspect Today",
  "hero.storm.subheading": "Fast documentation and insurance support so you can move quickly with confidence.",
  "hero.storm.cta": "Emergency Contact",
  "hero.storm.phone": "Call (555) 012-8891",
  "badge.licensed": "Licensed",
  "badge.insured": "Fully Insured",
  "badge.years": "25+ Years",
  "badge.response": "Answers In Under 10 Minutes",
  "review.aggregate_rating": "4.8 out of 5",
  "review.review_count": "247 reviews",
  "review.source": "Google",
  "section.services.title": "Roofing Services Built For Reliability",
  "section.projects.title": "Recent Roofing Projects",
  "section.materials.title": "Compare Roofing Materials",
  "section.financing.title": "Financing And Warranty Confidence",
  "section.faq.title": "Common Questions",
  "section.contact.title": "Request An Inspection",
  "cta.band.title": "Ready To Protect Your Home?",
  "cta.band.description": "Book a no-pressure inspection and get a clear action plan.",
  "cta.band.button": "Book Inspection",
  "form.name": "Full Name",
  "form.phone": "Phone Number",
  "form.email": "Email Address",
  "form.address": "Property Address",
  "form.notes": "Project Notes",
  "form.submit": "Send Request",
  "form.success": "Thanks. Our team will reach out shortly.",
  "footer.phone": "(555) 012-8891",
  "footer.hours": "Mon-Sat · 7:00 AM - 8:00 PM",
  "footer.areas_served": "North Hills, Lakeview, Ridge Garden, East Canyon",
  "footer.copy": "All rights reserved.",
  "footer.attribution.text": "Built and Maintained by Growrix OS",
  "footer.attribution.url": "https://www.growrixos.com",
  "mobile.tab.home": "Home",
  "mobile.tab.services": "Services",
  "mobile.tab.cta": "Inspect",
  "mobile.tab.blog": "Guides",
  "mobile.tab.contact": "Contact",
  "auth.modal.signInTitle": "Sign In",
  "auth.modal.signUpTitle": "Create Account",
  "auth.modal.switchToSignIn": "Already have an account? Sign in",
  "auth.modal.switchToSignUp": "Need an account? Create one",
  "theme.toggle": "Toggle theme",
  "skip.link": "Skip to main content"
} as const;

export type SiteContentKey = keyof typeof siteContent;



